spring.datasource.url: jdbc:mysql://localhost:3306/diploma_skillbox?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&useSSL=false&useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
spring.liquibase.enabled: true
spring.datasource.username: root
hibernate.dialect: org.hibernate.dialect.MySQL8Dialect
spring.datasource.password: admin
spring.jpa.hibernate.ddl-auto: none